# Generated by Django

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0002_auto_update_student'),  # <- вставить эту строку
    ]

    operations = [
        # Закомментируйте или удалите операции удаления полей
        # migrations.RemoveField(
        #     model_name='student',
        #     name='is_registered',hihi
        # ),
        # migrations.RemoveField(
        #     model_name='student',
        #     name='parent_contact',
        # ),

        # Оставьте только добавление поля class_name, если его нет
        migrations.AddField(
            model_name='student',
            name='class_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Класс'),
        ),
    ]
